// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_adamant = "CgkIlc73mt4DEAIQJw"; // <GPGSID>
        public const string achievement_break_100_times = "CgkIlc73mt4DEAIQMw"; // <GPGSID>
        public const string achievement_lord_of_the_shinagawa = "CgkIlc73mt4DEAIQDQ"; // <GPGSID>
        public const string achievement_break_1000_times = "CgkIlc73mt4DEAIQNA"; // <GPGSID>
        public const string achievement_legend_of_tokyo = "CgkIlc73mt4DEAIQCA"; // <GPGSID>
        public const string achievement_lord_of_setagaya = "CgkIlc73mt4DEAIQCw"; // <GPGSID>
        public const string achievement_aid_1000_times = "CgkIlc73mt4DEAIQKw"; // <GPGSID>
        public const string achievement_lord_of_the_katsushika = "CgkIlc73mt4DEAIQHw"; // <GPGSID>
        public const string achievement_rich_person_iii = "CgkIlc73mt4DEAIQSA"; // <GPGSID>
        public const string achievement_lord_of_the_taito = "CgkIlc73mt4DEAIQGA"; // <GPGSID>
        public const string achievement_lord_of_the_suginami = "CgkIlc73mt4DEAIQEA"; // <GPGSID>
        public const string achievement_attack_10000_times = "CgkIlc73mt4DEAIQOA"; // <GPGSID>
        public const string achievement_hire_iii = "CgkIlc73mt4DEAIQPw"; // <GPGSID>
        public const string achievement_hire_iv = "CgkIlc73mt4DEAIQQA"; // <GPGSID>
        public const string achievement_famous_in_tokyo = "CgkIlc73mt4DEAIQBw"; // <GPGSID>
        public const string achievement_hire_i = "CgkIlc73mt4DEAIQPQ"; // <GPGSID>
        public const string achievement_attack_1000_times = "CgkIlc73mt4DEAIQNw"; // <GPGSID>
        public const string achievement_aid_100_times = "CgkIlc73mt4DEAIQKg"; // <GPGSID>
        public const string achievement_rich_person_iv = "CgkIlc73mt4DEAIQSQ"; // <GPGSID>
        public const string achievement_ally_100_times = "CgkIlc73mt4DEAIQMA"; // <GPGSID>
        public const string achievement_break_10000_times = "CgkIlc73mt4DEAIQNQ"; // <GPGSID>
        public const string achievement_rich_person_ii = "CgkIlc73mt4DEAIQRw"; // <GPGSID>
        public const string leaderboard_def_rank = "CgkIlc73mt4DEAIQAw"; // <GPGSID>
        public const string leaderboard_hall_of_fame = "CgkIlc73mt4DEAIQBA"; // <GPGSID>
        public const string achievement_lord_of_the_adachi = "CgkIlc73mt4DEAIQIA"; // <GPGSID>
        public const string achievement_lord_of_the_chiyoda = "CgkIlc73mt4DEAIQEw"; // <GPGSID>
        public const string achievement_attack_100_times = "CgkIlc73mt4DEAIQNg"; // <GPGSID>
        public const string achievement_reaper = "CgkIlc73mt4DEAIQJA"; // <GPGSID>
        public const string achievement_a_novice_fighter = "CgkIlc73mt4DEAIQQg"; // <GPGSID>
        public const string achievement_lord_of_the_nerima = "CgkIlc73mt4DEAIQGw"; // <GPGSID>
        public const string achievement_lord_of_the_kita = "CgkIlc73mt4DEAIQHQ"; // <GPGSID>
        public const string achievement_the_wind_of_fighter = "CgkIlc73mt4DEAIQIw"; // <GPGSID>
        public const string achievement_lord_of_the_koto = "CgkIlc73mt4DEAIQFQ"; // <GPGSID>
        public const string achievement_lord_of_the_nakano = "CgkIlc73mt4DEAIQEQ"; // <GPGSID>
        public const string achievement_lord_of_the_chuo = "CgkIlc73mt4DEAIQFA"; // <GPGSID>
        public const string achievement_immortal = "CgkIlc73mt4DEAIQKA"; // <GPGSID>
        public const string achievement_king_of_tokyo = "CgkIlc73mt4DEAIQCQ"; // <GPGSID>
        public const string achievement_street_fighter = "CgkIlc73mt4DEAIQIg"; // <GPGSID>
        public const string achievement_hire_ii = "CgkIlc73mt4DEAIQPg"; // <GPGSID>
        public const string achievement_aid_10000_times = "CgkIlc73mt4DEAIQLA"; // <GPGSID>
        public const string leaderboard_atk_rank = "CgkIlc73mt4DEAIQAg"; // <GPGSID>
        public const string achievement_lord_of_the_meguro = "CgkIlc73mt4DEAIQDA"; // <GPGSID>
        public const string leaderboard_richest_rank = "CgkIlc73mt4DEAIQRQ"; // <GPGSID>
        public const string achievement_build_i = "CgkIlc73mt4DEAIQOQ"; // <GPGSID>
        public const string achievement_collect_1000_times = "CgkIlc73mt4DEAIQLg"; // <GPGSID>
        public const string achievement_crusaders = "CgkIlc73mt4DEAIQJQ"; // <GPGSID>
        public const string achievement_lord_of_the_shibuya = "CgkIlc73mt4DEAIQDw"; // <GPGSID>
        public const string achievement_strong_man = "CgkIlc73mt4DEAIQIQ"; // <GPGSID>
        public const string achievement_lord_of_the_minato = "CgkIlc73mt4DEAIQDg"; // <GPGSID>
        public const string achievement_aegis = "CgkIlc73mt4DEAIQJg"; // <GPGSID>
        public const string achievement_lord_of_the_shinjuku = "CgkIlc73mt4DEAIQEg"; // <GPGSID>
        public const string achievement_a_novice_tanker = "CgkIlc73mt4DEAIQQw"; // <GPGSID>
        public const string achievement_build_ii = "CgkIlc73mt4DEAIQOg"; // <GPGSID>
        public const string achievement_build_iii = "CgkIlc73mt4DEAIQOw"; // <GPGSID>
        public const string achievement_collect_100_times = "CgkIlc73mt4DEAIQLQ"; // <GPGSID>
        public const string achievement_lord_of_oda = "CgkIlc73mt4DEAIQCg"; // <GPGSID>
        public const string achievement_lord_of_the_itabashi = "CgkIlc73mt4DEAIQHA"; // <GPGSID>
        public const string achievement_rich_person_i = "CgkIlc73mt4DEAIQRg"; // <GPGSID>
        public const string achievement_the_first_unification = "CgkIlc73mt4DEAIQAQ"; // <GPGSID>
        public const string achievement_collect_10000_times = "CgkIlc73mt4DEAIQLw"; // <GPGSID>
        public const string achievement_lord_of_the_arakawa = "CgkIlc73mt4DEAIQHg"; // <GPGSID>
        public const string achievement_lord_of_the_dosima = "CgkIlc73mt4DEAIQGg"; // <GPGSID>
        public const string achievement_lord_of_the_sumida = "CgkIlc73mt4DEAIQFw"; // <GPGSID>
        public const string achievement_build_iv = "CgkIlc73mt4DEAIQPA"; // <GPGSID>
        public const string achievement_lord_of_the_edogawa = "CgkIlc73mt4DEAIQFg"; // <GPGSID>
        public const string achievement_ally_10000_times = "CgkIlc73mt4DEAIQMg"; // <GPGSID>
        public const string achievement_ally_1000_times = "CgkIlc73mt4DEAIQMQ"; // <GPGSID>
        public const string achievement_rich_person_v = "CgkIlc73mt4DEAIQSg"; // <GPGSID>
        public const string achievement_lord_of_the_bunkyo = "CgkIlc73mt4DEAIQGQ"; // <GPGSID>

}

